CREATE TABLE STUDENT (
    ID  INTEGER  PRIMARY KEY  AUTOINCREMENT , 
    NAME_ VARCHAR(50) , 
    AGE INT , 
    SCHOOL_NUMBER INT UNIQUE
);

CREATE TABLE TEACHER (
    ID  INTEGER  PRIMARY KEY  AUTOINCREMENT , 
    NAME_ VARCHAR(50) , 
    AGE INT ,
    SCHOOL_NUMBER INT UNIQUE
);

CREATE TABLE school_number_trigger(
    ID INTEGER  PRIMARY KEY  AUTOINCREMENT , 
    school_number INT 
);



